[general]
import = ["/Users/danielhess/.alacritty/themes/horizon-dark.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 10

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 12.0

[font.normal]
family = "DejaVuSansMono Nerd Font Mono"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[window]
decorations = "full"
opacity = 1.0
startup_mode = "Fullscreen"
